name:                Exercises01
version:             0.1.0.0
github:              "dalvescb/Exercises01"
license:             BSD3
author:              "Curtis D&#39;Alves"
maintainer:          "curtis.dalves@gmail.com"
copyright:           "copyright: (c) 2019 Curtis D&#39;Alves"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            None

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/dalvescb/Exercises01#readme>

dependencies:
- base >= 4.7 && < 5
- QuickCheck

library:
  source-dirs: src

executables:
  Exercises01-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Exercises01

tests:
  Exercises01-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Exercises01
